Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/UnneededCopDisableDirective:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/production.rb'
    - 'app/services/import_old_database_service/**/*'

Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: true
  Max: 16
  Exclude:
    - 'db/migrate/*.rb'

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ClassLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/OutputSafety:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

AllCops:
  Exclude:
    - "db/**/*"
    - "Gemfile"
    - "vendor/**/*"
    - "tmp/**/*"
    - "config/**/*"
    - "bin/**"
    - "**/*.axlsx"
