image: ruby:2.5.0
pipelines:
  default:
    - step:
        script:
          - export DEALBOOK_DATABASE_HOST=localhost
          - export DEALBOOK_DATABASE_USER=dealbook
          - export DEALBOOK_DATABASE_PASSWORD=dealbook
          - export RAILS_ENV=test
          - bin/setup
          - bundle exec rspec spec
        services:
          - postgres
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: dealbook_test
        POSTGRES_USER: dealbook
        POSTGRES_PASSWORD: dealbook
