# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fad00bca620f595b68d8c2c68758d71a597b7327e002356470f2a15f0ea4ab093285e85deec95caef878df472c1f9742379e07f9c76788a9fc5d4cd1ee40d591

test:
  secret_key_base: ddf30e80812e4638d3a4d83bf52c62001feaeed145ebc3e466f9ff551ddff08ed57ec58b44da7f36875e0ae3afac7882004fdef44852fc09a4ce352e2b08590a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
