class CreateCompanySicCodes < ActiveRecord::Migration[5.1]
  def change
    create_table :company_sic_codes, {:id => false} do |t|
      t.integer :code, :null => false, index: true
      t.string :description

      t.timestamps
    end

    CompanySicCode.create :code => 01, :description => "Agricultural Production – Crops"
    CompanySicCode.create :code => 02, :description => "Agricultural Production – Livestock"
    CompanySicCode.create :code => 07, :description => "Agricultural Services"
    CompanySicCode.create :code => 08, :description => "Forestry"
    CompanySicCode.create :code => 09, :description => "Fishing, Hunting, & Trapping"
    CompanySicCode.create :code => 10, :description => "Metal, Mining"
    CompanySicCode.create :code => 12, :description => "Coal Mining"
    CompanySicCode.create :code => 13, :description => "Oil & Gas Extraction"
    CompanySicCode.create :code => 14, :description => "Nonmetallic Minerals, Except Fuels"
    CompanySicCode.create :code => 15, :description => "General Building Contractors"
    CompanySicCode.create :code => 16, :description => "Heavy Construction, Except Building"
    CompanySicCode.create :code => 17, :description => "Special Trade Contractors"
    CompanySicCode.create :code => 20, :description => "Food & Kindred Products"
    CompanySicCode.create :code => 21, :description => "Tobacco Products"
    CompanySicCode.create :code => 22, :description => "Textile Mill Products"
    CompanySicCode.create :code => 23, :description => "Apparel & Other Textile Products"
    CompanySicCode.create :code => 24, :description => "Lumber & Wood Products"
    CompanySicCode.create :code => 25, :description => "Furniture & Fixtures"
    CompanySicCode.create :code => 26, :description => "Paper & Allied Products"
    CompanySicCode.create :code => 27, :description => "Printing & Publishing"
    CompanySicCode.create :code => 28, :description => "Chemical & Allied Products"
    CompanySicCode.create :code => 29, :description => "Petroleum & Coal Products"
    CompanySicCode.create :code => 30, :description => "Rubber & Miscellaneous Plastics Products"
    CompanySicCode.create :code => 31, :description => "Leather & Leather Products"
    CompanySicCode.create :code => 32, :description => "Stone, Clay, & Glass Products"
    CompanySicCode.create :code => 33, :description => "Primary Metal Industries"
    CompanySicCode.create :code => 34, :description => "Fabricated Metal Products"
    CompanySicCode.create :code => 35, :description => "Industrial Machinery & Equipment"
    CompanySicCode.create :code => 36, :description => "Electronic & Other Electric Equipment"
    CompanySicCode.create :code => 37, :description => "Transportation Equipment"
    CompanySicCode.create :code => 38, :description => "Instruments & Related Products"
    CompanySicCode.create :code => 39, :description => "Miscellaneous Manufacturing Industries"
    CompanySicCode.create :code => 40, :description => "Railroad Transportation"
    CompanySicCode.create :code => 41, :description => "Local & Interurban Passenger Transit"
    CompanySicCode.create :code => 42, :description => "Trucking & Warehousing"
    CompanySicCode.create :code => 43, :description => "U.S. Postal Service"
    CompanySicCode.create :code => 44, :description => "Water Transportation"
    CompanySicCode.create :code => 45, :description => "Transportation by Air"
    CompanySicCode.create :code => 46, :description => "Pipelines, Except Natural Gas"
    CompanySicCode.create :code => 47, :description => "Transportation Services"
    CompanySicCode.create :code => 48, :description => "Communications"
    CompanySicCode.create :code => 49, :description => "Electric, Gas, & Sanitary Services"
    CompanySicCode.create :code => 50, :description => "Wholesale Trade – Durable Goods"
    CompanySicCode.create :code => 51, :description => "Wholesale Trade – Nondurable Goods"
    CompanySicCode.create :code => 52, :description => "Building Materials & Gardening Supplies"
    CompanySicCode.create :code => 53, :description => "General Merchandise Stores"
    CompanySicCode.create :code => 54, :description => "Food Stores"
    CompanySicCode.create :code => 55, :description => "Automative Dealers & Service Stations"
    CompanySicCode.create :code => 56, :description => "Apparel & Accessory Stores"
    CompanySicCode.create :code => 57, :description => "Furniture & Homefurnishings Stores"
    CompanySicCode.create :code => 58, :description => "Eating & Drinking Places"
    CompanySicCode.create :code => 59, :description => "Miscellaneous Retail"
    CompanySicCode.create :code => 60, :description => "Depository Institutions"
    CompanySicCode.create :code => 61, :description => "Nondepository Institutions"
    CompanySicCode.create :code => 62, :description => "Security & Commodity Brokers"
    CompanySicCode.create :code => 63, :description => "Insurance Carriers"
    CompanySicCode.create :code => 64, :description => "Insurance Agents, Brokers, & Service"
    CompanySicCode.create :code => 65, :description => "Real Estate"
    CompanySicCode.create :code => 67, :description => "Holding & Other Investment Offices"
    CompanySicCode.create :code => 70, :description => "Hotels & Other Lodging Places"
    CompanySicCode.create :code => 72, :description => "Personal Services"
    CompanySicCode.create :code => 73, :description => "Business Services"
    CompanySicCode.create :code => 75, :description => "Auto Repair, Services, & Parking"
    CompanySicCode.create :code => 76, :description => "Miscellaneous Repair Services"
    CompanySicCode.create :code => 78, :description => "Motion Pictures"
    CompanySicCode.create :code => 79, :description => "Amusement & Recreation Services"
    CompanySicCode.create :code => 80, :description => "Health Services"
    CompanySicCode.create :code => 81, :description => "Legal Services"
    CompanySicCode.create :code => 82, :description => "Educational Services"
    CompanySicCode.create :code => 83, :description => "Social Services"
    CompanySicCode.create :code => 84, :description => "Museums, Botanical, Zoological Gardens"
    CompanySicCode.create :code => 86, :description => "Membership Organizations"
    CompanySicCode.create :code => 87, :description => "Engineering & Management Services"
    CompanySicCode.create :code => 88, :description => "Private Households"
    CompanySicCode.create :code => 89, :description => "Services, Not Elsewhere Classified"
    CompanySicCode.create :code => 91, :description => "Executive, Legislative, & General"
    CompanySicCode.create :code => 92, :description => "Justice, Public Order, & Safety"
    CompanySicCode.create :code => 93, :description => "Finance, Taxation, & Monetary Policy"
    CompanySicCode.create :code => 94, :description => "Administration of Human Resources"
    CompanySicCode.create :code => 95, :description => "Environmental Quality & Housing"
    CompanySicCode.create :code => 96, :description => "Administration of Economic Programs"
    CompanySicCode.create :code => 97, :description => "National Security & International Affairs"
    CompanySicCode.create :code => 98, :description => "Zoological Gardens"
    CompanySicCode.create :code => 99, :description => "Non-Classifiable Establishments"

  end
end
